//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpSeleniumTemplate.Queries {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TarefasQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TarefasQueries() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSharpSeleniumTemplate.Queries.TarefasQueries", typeof(TarefasQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TRUNCATE mantis_bug_table;
        ///TRUNCATE mantis_bug_text_table;
        ///TRUNCATE mantis_bug_history_table;
        ///TRUNCATE mantis_bugnote_table;
        ///TRUNCATE mantis_bugnote_text_table;
        ///TRUNCATE mantis_bug_file_table;
        ///TRUNCATE mantis_bug_monitor_table;
        ///TRUNCATE mantis_bug_relationship_table;
        ///TRUNCATE mantis_bug_revision_table;
        ///TRUNCATE mantis_bug_tag_table;.
        /// </summary>
        internal static string DeletaTodasTarefas {
            get {
                return ResourceManager.GetString("DeletaTodasTarefas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO mantis_bug_text_table(id, description,steps_to_reproduce,additional_information)
        ///VALUES(99,&apos;$descricaoTarefa&apos;,&apos;passos para reproduzir erro&apos;,&apos;informacao adicional&apos;);
        ///
        ///INSERT INTO mantis_bug_table(project_id, reporter_id,priority,severity,reproducibility,STATUS,resolution,projection,eta,bug_text_id,view_state,summary,category_id,due_date)
        ///VALUES(1,1,30,50,70,10,10,10,10,99,10,&apos;$resumoTarefa&apos;,1,1);
        ///
        ///INSERT INTO mantis_bug_history_table(user_id, bug_id,field_name,old_value,new_value,type)
        ///VAL [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string InserirTarefa {
            get {
                return ResourceManager.GetString("InserirTarefa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO mantis_bug_text_table(id, description,steps_to_reproduce,additional_information)
        ///VALUES(99,&apos;$descricaoTarefa&apos;,&apos;passos para reproduzir erro&apos;,&apos;informacao adicional&apos;);
        ///
        ///INSERT INTO mantis_bug_table(project_id, reporter_id,priority,severity,reproducibility,STATUS,resolution,projection,eta,bug_text_id,view_state,summary,category_id,due_date)
        ///VALUES(1,1,30,50,70,10,10,10,10,99,10,&apos;$resumoTarefa&apos;,1,1);
        ///
        ///INSERT INTO mantis_bug_history_table(user_id, bug_id,field_name,old_value,new_value,type)
        ///VAL [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string InseriVariasTarefas {
            get {
                return ResourceManager.GetString("InseriVariasTarefas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a select * FROM mantis_bug_table mbt
        ///INNER JOIN mantis_bug_text_table mbtt
        ///ON mbt.bug_text_id=mbtt.id
        ///WHERE mbt.summary=&apos;resumo tarefa&apos; AND mbtt.description=&apos;descricao tarefa&apos;;.
        /// </summary>
        internal static string RetornaTarefa {
            get {
                return ResourceManager.GetString("RetornaTarefa", resourceCulture);
            }
        }
    }
}
